name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "12 8 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: bc6476437303823e1fec3d48f6759bc3
          TIMEZONE: Asia/Seoul
